version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "6000:6000"

  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    depends_on:
      - api